### ISSUE TITLE
Test model with custom data

### ISSUE THREAD

**Issue by yicheng6o6** [idiap/residual_pose#2]
Hi, Thank you for the great work.

I have depth images and I'm wondering how to convert it into .npy or .mat file? I can use some tools transform depth images to .mat files, but when I test model with these data, I got **KeyError: 'depth'** information.

I would be grateful if you could give me some suggestions to achieve it.

Best wishes,
Yicheng

**Comment by af-doom** [comment]
> Hi, Thank you for the great work.
> 
> I have depth images and I'm wondering how to convert it into .npy or .mat file? I can use some tools transform depth images to .mat files, but when I test model with these data, I got **KeyError: 'depth'** information.
> 
> I would be grateful if you could give me some suggestions to achieve it.
> 
> Best wishes, Yicheng

hello bron i also have this question

**Comment by legan78** [comment]
Hi,

The load image utils expects a dictionary when file format is given in .mat. A .mat file also stores data in a dictionary style. You can create the dictionary with `img_dict = {'depth': my_depth_image_array}` and save them with scipy (.mat). See [here](https://github.com/idiap/residual_pose/blob/05404a9d82dc9dd0ed5e918f8df54a5b6bbf82fb/Utils.py#L117) how the different image formats are loaded.

Hope it helps

**Comment by af-doom** [comment]
> Hi,
> 
> The load image utils expects a dictionary when file format is given in .mat. A .mat file also stores data in a dictionary style. You can create the dictionary with `img_dict = {'depth': my_depth_image_array}` and save them with scipy (.mat). See [here](https://github.com/idiap/residual_pose/blob/05404a9d82dc9dd0ed5e918f8df54a5b6bbf82fb/Utils.py#L117) how the different image formats are loaded.
> 
> Hope it helps

thank you very much for your reply,but  i have a new problem
I use this  commmand:
 
python main.py --config_file config/itop_config_file.json \ --image_sample img_samples/itop/tset.png  \ --output_path output_dir
    Traceback (most recent call last):
  File "main.py", line 209, in <module>
    detections, canvas2d= detect_2d_pose(img_depth, hg_model, config)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "main.py", line 104, in detect_2d_pose
    output, feats= hg_model(img_inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/MyFiles/residual_pose-master/HourGlass.py", line 268, in forward
    in_features= self.front(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight 64 1 7 7, but got 5-dimensional input of size [1, 1, 256, 320, 3] instead

**Comment by legan78** [comment]
Hi,
Input depth image is expected to have shape [1, 1, width, height]

**Comment by yicheng6o6** [comment]
Hi, @af-doom, @legan78, thank you for your reply:)

I tested my depth images and I met this error:
```
Traceback (most recent call last):
  File "main.py", line 204, in <module>
    img_color= cv2.cvtColor(img_color, cv2.COLOR_GRAY2BGR)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-xw6jtoah/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 3
```

Besides, I'm not sure about how to convert my depth images into [1, 1, width, height]. May I have your suggestions to fix these problems?
Any help is much appreciated!

**Comment by yicheng6o6** [comment]
Hi, @legan78, now I can test my own depth images.

One of the results like the following figure:
![canvas_3d_regressed](https://user-images.githubusercontent.com/92355515/171436900-70fad71d-0a2a-4a33-ba4f-1a2a0efe3d5a.jpg)
And I use this command to test: `python main.py --config_file config/itop_config_file.json                --image_sample /home/lk3696/residual_pose/depth85.npy                --output_path output_dir5`

My depth image size: 320x240 and I convert .png file into .npy.

May I have your suggestions to get better results?
Any help is much appreciated!
